# Generated by Django 5.1.6 on 2025-02-26 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название подразделения', max_length=255, unique=True, verbose_name='Название подразделения')),
                ('parent', models.ForeignKey(blank=True, help_text='Укажите родительское подразделение', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subdepartments', to='employees.department', verbose_name='Родительское подразделение')),
            ],
            options={
                'verbose_name': 'Подразделения',
                'verbose_name_plural': 'Подразделения',
                'ordering': ['pk', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Введите ФИО', max_length=255, verbose_name='ФИО')),
                ('position', models.CharField(help_text='Укажите должность', max_length=255, verbose_name='Должность')),
                ('hire_date', models.DateField(help_text='Укажите дату приема на работу', verbose_name='Дата приема на работу')),
                ('salary', models.DecimalField(decimal_places=2, help_text='Укажите размер заработной платы', max_digits=10, verbose_name='Размер заработной платы')),
                ('department', models.ForeignKey(help_text='Укажите подразделение', on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='employees.department', verbose_name='Подразделение')),
            ],
            options={
                'verbose_name': 'Работники',
                'verbose_name_plural': 'Работники',
                'ordering': ['pk', 'full_name'],
            },
        ),
    ]
